/*
 * Very basic JavaBean cache
 * Created on 4 févr. 2016 ( Date ISO 2016-02-04 - Time 13:41:24 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package org.demo.cache;

import java.util.Hashtable;
import java.util.Map;

import org.demo.bean.Entity1 ;

/**
 * Very basic cache for Entity1 instances (just for the Telosys Tools demo)
 * 
 * @author Telosys Tools StatisticsSnapshotGenerator
 *
 */
public class Entity1Cache
{
	private final static Map<String,Entity1> cache = new Hashtable<String,Entity1>() ;
	
	/**
	 * Build the cache key from the Primary Key field(s)
	 * @return the key
	 */
	private final static String getKey(  ) {
		return ""  ;
	}

	/**
	 * Put the given Entity1 instance in the cache
	 * @param Entity1 instance to be stored
	 */
	public final static void putEntity1(Entity1 entity1 ) {
		String key = getKey(  ) ;
		cache.put(key, entity1 );
	}
	
	/**
	 * Get the Entity1 instance for the given primary key
	 * @return the Entity1 instance (or null if none)
	 */
	public final static Entity1 getEntity1(  ) {
		String key = getKey(  ) ;
		return cache.get(key);
	}

	/**
	 * Removes the Entity1 associated with the given primary key
	 */
	public final static void removeEntity1 (  ) {
		String key = getKey(  ) ;
		cache.remove(key);
	}
	
	/**
	 * Removes the given Entity1 from the cache using its primary key
	 * @param Entity1 instance to be removed
	 */
	public final static void removeEntity1 (Entity1 entity1 ) { 
		String key = getKey(  ) ;
		cache.remove(key);
	}

}
