/*
 * Very basic JavaBean cache
 * Created on 29 mars 2016 ( Date ISO 2016-03-29 - Time 15:38:31 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package org.demo.cache;

import java.util.Hashtable;
import java.util.Map;

import org.demo.bean.En ;

/**
 * Very basic cache for En instances (just for the Telosys Tools demo)
 * 
 * @author Telosys Tools StatisticsSnapshotGenerator
 *
 */
public class EnCache
{
	private final static Map<String,En> cache = new Hashtable<String,En>() ;
	
	/**
	 * Build the cache key from the Primary Key field(s)
	 * @return the key
	 */
	private final static String getKey(  ) {
		return ""  ;
	}

	/**
	 * Put the given En instance in the cache
	 * @param En instance to be stored
	 */
	public final static void putEn(En en ) {
		String key = getKey(  ) ;
		cache.put(key, en );
	}
	
	/**
	 * Get the En instance for the given primary key
	 * @return the En instance (or null if none)
	 */
	public final static En getEn(  ) {
		String key = getKey(  ) ;
		return cache.get(key);
	}

	/**
	 * Removes the En associated with the given primary key
	 */
	public final static void removeEn (  ) {
		String key = getKey(  ) ;
		cache.remove(key);
	}
	
	/**
	 * Removes the given En from the cache using its primary key
	 * @param En instance to be removed
	 */
	public final static void removeEn (En en ) { 
		String key = getKey(  ) ;
		cache.remove(key);
	}

}
