/*
 * JUnit test case for Sdf caching service
 * Created on 29 mars 2016 ( Date ISO 2016-03-29 - Time 15:30:12 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package org.demo.test.cache;


import org.demo.bean.Sdf ;
import org.demo.cache.SdfCache ;

import org.junit.Assert;
import org.junit.Test;

/**
 * JUnit test case for Sdf caching service
 * 
 * @author Telosys Tools StatisticsSnapshotGenerator
 *
 */
public class SdfCacheTest 
{
	protected static final java.util.Date now = new java.util.Date();

	private final static void populate(Sdf sdf) {
		sdf.setMyfield( "A" ) ;
	}

	@Test
	public void testPutGetRemove() {
		
		System.out.println("Testing class SdfCache ..." );
		
		Sdf sdf = new Sdf();
		populate(sdf);
		System.out.println("Entity populated : " + sdf );
		
		SdfCache.putSdf(sdf) ;	// Store in cache	
		
		Sdf sdf2 = SdfCache.getSdf(  );
		Assert.assertTrue( sdf == sdf2 ) ; // Same instance
		
		SdfCache.removeSdf(   ) ; // Remove from cache	
		
		Sdf sdf3 = SdfCache.getSdf(  );
		Assert.assertTrue( null == sdf3 ) ; // Not in cache
		
	}
}
