/*
 * Very basic JavaBean cache
 * Created on 29 mars 2016 ( Date ISO 2016-03-29 - Time 15:30:12 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package org.demo.cache;

import java.util.Hashtable;
import java.util.Map;

import org.demo.bean.Sdf ;

/**
 * Very basic cache for Sdf instances (just for the Telosys Tools demo)
 * 
 * @author Telosys Tools Generator
 *
 */
public class SdfCache
{
	private final static Map<String,Sdf> cache = new Hashtable<String,Sdf>() ;
	
	/**
	 * Build the cache key from the Primary Key field(s)
	 * @return the key
	 */
	private final static String getKey(  ) {
		return ""  ;
	}

	/**
	 * Put the given Sdf instance in the cache
	 * @param Sdf instance to be stored
	 */
	public final static void putSdf(Sdf sdf ) {
		String key = getKey(  ) ;
		cache.put(key, sdf );
	}
	
	/**
	 * Get the Sdf instance for the given primary key
	 * @return the Sdf instance (or null if none)
	 */
	public final static Sdf getSdf(  ) {
		String key = getKey(  ) ;
		return cache.get(key);
	}

	/**
	 * Removes the Sdf associated with the given primary key
	 */
	public final static void removeSdf (  ) {
		String key = getKey(  ) ;
		cache.remove(key);
	}
	
	/**
	 * Removes the given Sdf from the cache using its primary key
	 * @param Sdf instance to be removed
	 */
	public final static void removeSdf (Sdf sdf ) { 
		String key = getKey(  ) ;
		cache.remove(key);
	}

}
