/*
 * JUnit test case for En caching service
 * Created on 29 mars 2016 ( Date ISO 2016-03-29 - Time 15:38:31 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package org.demo.test.cache;


import org.demo.bean.En ;
import org.demo.cache.EnCache ;

import org.junit.Assert;
import org.junit.Test;

/**
 * JUnit test case for En caching service
 * 
 * @author Telosys Tools Generator
 *
 */
public class EnCacheTest 
{
	protected static final java.util.Date now = new java.util.Date();

	private final static void populate(En en) {
		en.setMyfield( "A" ) ;
	}

	@Test
	public void testPutGetRemove() {
		
		System.out.println("Testing class EnCache ..." );
		
		En en = new En();
		populate(en);
		System.out.println("Entity populated : " + en );
		
		EnCache.putEn(en) ;	// Store in cache	
		
		En en2 = EnCache.getEn(  );
		Assert.assertTrue( en == en2 ) ; // Same instance
		
		EnCache.removeEn(   ) ; // Remove from cache	
		
		En en3 = EnCache.getEn(  );
		Assert.assertTrue( null == en3 ) ; // Not in cache
		
	}
}
